[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Humboldt-WI/bads/blob/master/exercises/1_ex_python.ipynb) 

# BADS Exercise 1 on Python programming
We covered a lot of concepts in the first [demo notebook on Python programming](https://github.com/Humboldt-WI/bads/blob/master/demo_notebooks/1_nb_python_intro.ipynb). Solving the exercises allows you to test your familiarity with these concepts.  

## Variables, assignments, and comparisons

1. Create two variables $a$ and $b$ and assign values of $3$ and $4.5$.

In [12]:
a = 3
b = 4.5

2. Query the type of variable $a$.

In [13]:
print(type(a))

<class 'int'>


3. Check whether variable $b$ is a text variable.

In [14]:
type(b) == str

False

4. Calculate $a^2 + \frac{1}{b}$, $\sqrt{a*b}$, and $log_2(a)$.

In [15]:
a**2 + 1/b

9.222222222222221

In [16]:
import numpy as np
np.sqrt(a*b)

3.6742346141747673

In [17]:
np.log2(a)

1.584962500721156

## Matrix algebra
Create three additional variables as follows:

 $$ A = \left( \begin{matrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 10 \end{matrix} \right) \quad
  B = \left( \begin{matrix} 1 & 4 & 7 \\ 2 & 5 & 8 \\ 3 & 6 & 9 \end{matrix} \right)  \quad
  y = \left( \begin{matrix} 1 \\ 2 \\ 3 \end{matrix} \right) $$

In [90]:
# Code to create variables A, B, and y

A = np.array([[1, 2, 3,],
              [4, 5, 6],
              [7, 8, 10]])

B = np.array([[1, 4, 7,],
              [2, 5, 8],
              [3, 6, 9]])

y = np.array([1, 2, 3])

Perform the following operations. Note that mathematical operators like `*` might not behave in the way you need it. Wasn't there a powerful library for all sorts of numerical computations including classic linear algebra?

Calculate  

  1. $a*A$

In [91]:
np.dot(a, A)

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 30]])

  2. $A*B$

In [92]:
np.matmul(A, B)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 53, 128, 203]])

  3. The inverse of matrix $A$ and store the result in a variable $invA$. Any ideas how to get Python to invert a matrix?
> Hint: NumPy is your friend.  

In [93]:
invA=np.linalg.inv(A)
print(invA)

[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]


  4. Multiply $A$ and $invA$ and verify that the result is the identity matrix (i.e. only 1s on the diagonal). You'll probably find that it isn't, because computers usually make very small rounding errors when handling real numbers. The reason is interesting, but you'll have to look it up if you're interested.

In [94]:
np.dot(A, invA)

array([[ 1.00000000e+00, -4.44089210e-16, -1.11022302e-16],
       [ 4.44089210e-16,  1.00000000e+00, -2.22044605e-16],
       [ 4.44089210e-16,  8.88178420e-16,  1.00000000e+00]])

  5. The transpose of matrix $B$

In [28]:
np.transpose(B)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

  6. Fill the first row of matrix $B$ with ones

In [95]:
B[0, :] = [1, 1, 1] 
print(B)

[[1 1 1]
 [2 5 8]
 [3 6 9]]


  7. Calculate the ordinary least squares estimator $\beta$ (i.e. a standard regression) 
$$ \beta = (A^{\top}A)^{-1}A^{\top} y $$ 
Run a web search for "Python matrix transpose" to get help on how to transpose a matrix. 

In [96]:
tA = np.transpose(A)
tA_A = np.dot(tA, A)
i_tA_A = np.linalg.inv(tA_A)
beta = np.dot(np.dot(i_tA_A, tA), y)
print(beta)

[-3.33333333e-01  6.66666667e-01 -1.68753900e-14]


In [97]:
beta = np.linalg.inv(A.T @ A) @ A.T @ y
print(beta)

[-3.33333333e-01  6.66666667e-01 -1.68753900e-14]


## Indexing
1. Look at values of variables $A$, $B$, and $y$ from the last exercise

In [98]:
print(A)
print(B)
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
[[1 1 1]
 [2 5 8]
 [3 6 9]]
[1 2 3]


2. Access the second element in the third row of $A$ and the first element in the second row of $B$, and compute their product

In [99]:
A[2, 1] * B[1, 0]

16

3. Multiply the first row of $A$ and the third column of $B$

In [100]:
A[0, :] * B[:, 2]

array([ 1, 16, 27])

4. Access the elements of y that are greater than 1 (without looking up their position manually)

In [101]:
y[y>1]

array([2, 3])

5. Access the elements of A in the second column, for which the values in the first column are greater or equal to 4.

In [102]:
A[A[:, 1] >= 4, 1]

array([5, 8])

In [103]:
A[1:3]

array([[ 4,  5,  6],
       [ 7,  8, 10]])

6. Access the 4th row of A. If this returns an error message, use Google to investigate the problem and find out what went wrong.

In [62]:
# A[4, :]
# won't work because A has only 3 rows -> 2 is the hights as index number python will accept

## Custom functions
For many statistical applications it is practical to standardize variable values. One way to standardize is *centering and scaling*. In simple words, we make the variables comparable by reducing them to the same scale.

Start with implementing a custom function. Your function should take an argument **x**. To keep things simple, we expect x to always be a numeric vector (and not text or a matrix, for example). In the body of the function, calculate the mean and standard deviation of **x**. Store the results in variables  **mu** and **std**, respectively. Then for each element in the vector, substract the mean and divide by the standard deviation.
$$ x_{new} = \frac{x-\mu}{std}$$
Make sure your functions **returns** the standardized vector (i.e., $x_new$ in the equation) as result. You might want to import `NumPy` for calculating the mean and standard deviation.

In [104]:

def standardize(x):
    if not isinstance(x, (np.ndarray, np.number)):
        raise ValueError("Input must be a NumPy array.")
    mu = np.mean(x)
    std = np.std(x)
    x_new = (x - mu)/std
    return x_new

You should always test your functions. Create a vector **a** with the elements (-100, -25, -10, 0, 10, 25, 100) and check if your function produces the correct result.     

*Optional*: Create a vector **b** with elements ("1", "2", "3") and check the function. Let's include a simple check in the function and give feedback. Before doing any calculations, use `if()` and `type()` to check if the input is a numeric vector. There are many ways to code the condition *x is numeric* in Python. Run a quick web search and use a simple approach. If the input is not numeric, skip the computations and print a message "input not numeric".

In [108]:
t = np.array([-100, -25, -10, 0, 10, 25, 100])
print(t)

t_sdz = standardize(t)
print(t_sdz)

# t_new = np.array(['a', 'b', 'c'])
# t_new_sdz = standardize(t_new)


[-100  -25  -10    0   10   25  100]
[-1.80648921 -0.4516223  -0.18064892  0.          0.18064892  0.4516223
  1.80648921]


## Data structures 
Say you want to keep track of the members of the four houses of the famous Hogwarts School of Witchcraft and Wizardry. What might be a suitable data structure? We create a dictionary named **hogwarts** and use the names of the houses as keys. Then, the values associated with those keys could be any type that supports storing a set of strings, i.e., to store the names of house members. Draw on your knowledge of Python dictionaries and lists to implement such a data structure. Populate the dictionary with the following data, and feel free to add more characters if you wish. 

- Gryffindor: I'm sure you know many members of that house 
- Hufflepuff: notable members include Newt Scamander, Cedric Diggory and Nymphadora Tonks
- Ravenclaw: here we've got, e.g. Luna Lovegood, Gilderoy Lockhart and Filius Flitwick
- Slytherin: Draco Malfoy, Vincent Crabbe, Gregory Goyle, and of course the one that must not be named

In [119]:
hogwarts = {
    'griffendor': ['harry', 'ron', 'hermine'],
    'hufflepuff': ['newt', 'cecdric', 'nymphadora'],
    'ravenclaw': ['luna', 'gulderoy', 'filius'],
    'slytherin': ['draco', 'vicent', 'gregory']
}
hogwarts

{'griffendor': ['harry', 'ron', 'hermine'],
 'hufflepuff': ['newt', 'cecdric', 'nymphadora'],
 'ravenclaw': ['luna', 'gulderoy', 'filius'],
 'slytherin': ['draco', 'vicent', 'gregory']}

Dictionaries are really useful. Still our above data structure is limited. We can only store the name of a witch or wizard. Wouldn't it be cool to be able to store more information, something like her/his favored charm, best friend, pet, etc. 

Think about how we could realize this functionality. Well, we could create yet another dictionary in which we use a witches's/wizard's name as key and as value some some other data structure in which we can store all the details we like. To our knowledge, the names of witches / wizards are unique in the Harry Potter universe, so that names could serve as (unique) keys; nerd alert. Still a dictionary of dictionaries sounds pretty complicated. In fact, the task we described above is a perfect use case for a custom class. Custom classes  allow us to store any piece of information about a person at one place. Furthermore, they would allow us to implement functions that process this information. So here is your next task:

Create a custom class wizard that facilitates storing the following properties
- First name
- Last name
- Pet
- Pet name
- Patronus shape


Also implement a method `tell_pet()`that prints an output of the following format:
*"Harry Potter's owl is called Hedwig."* <br> Note how the output makes use of information on the first and last name of the wizard and other pieces of information.

Implement one more  method `expecto_patronum()`. Calling that method for Harry would produce the output (print):
*"A stag appears."*

In [164]:
class wizard():

    """Wizard characteristics"""
    def __init__(self,
                firstname, 
                lastname,
                pet = None,
                petname = None,
                patronus = None ):

        self.firstname = firstname
        self.lastname = lastname
        self.pet = pet
        self.petname = petname
        self.patronus = patronus

    """Method to get the name of a wizard's pet"""
    def tell_pet(self):
        if self.pet is None or self.petname is None:
            print(self.firstname + " " + self.lastname + " has no pet.")
        else:
            print(self.firstname + " " + self.lastname + "'s " + self.pet.lower() + " is called " + self.petname + ".")

    """Method to get a wizard's patronus"""
    def expecto_patronum(self):
        if self.patronus is None:
            print(self.firstname + " " + self.lastname + " has no patronus.")
        else:
            print("A " + self.patronus.lower() + " appears.")


Update your dictionary with schools and their members. Instead of storing a list of names as values, your new dictionary should store a list of instances of the class wizard. Note that you need to create these instances first. So you need to create an instance of class wizard for Harry, another one for Ron, Malfoy, etc. In case your knowledge of the Potter universe is a bit shaky, just invent the data you need. Just in case, [here is a little refresher of the expecto patronum spell](https://www.insider.com/harry-potter-characters-patronus-2018-11).

In [165]:
harry = wizard(
    firstname = "Harry",
    lastname = "Potter",
    pet = "Owl",
    petname = "Hedwig",
    patronus = "Stag"
)

ron = wizard(
    firstname = "Ron",
    lastname = "Weasley",
    pet = "Scabbers",
    petname = "Martin",
    patronus = "Jack Russel Terrier"
)

draco = wizard(
    firstname = "Draco",
    lastname = "Melfoy",
    pet = "Owl",
    petname = "Buckbeak"
)

hermine = wizard(
    firstname = "Hermine",
    lastname = "Granger",
    patronus = "Otter"
)

luna = wizard(
    firstname = "Luna",
    lastname = "Lovegood",
    pet = "Pygmy Puff",
    petname = "Pigwidgeon",
    patronus = "Hare"
)

newt = wizard(
    firstname = "Newt",
    lastname = "Scamander"
)

hogwarts = {
    'griffendor': [harry, ron, hermine],
    'hufflepuff': [newt],
    'ravenclaw': [luna],
    'slytherin': [draco]
}
print(hogwarts)

{'griffendor': [<__main__.wizard object at 0x1439688d0>, <__main__.wizard object at 0x14396bd90>, <__main__.wizard object at 0x143968e90>], 'hufflepuff': [<__main__.wizard object at 0x14396b6d0>], 'ravenclaw': [<__main__.wizard object at 0x14396a750>], 'slytherin': [<__main__.wizard object at 0x14396a910>]}


In [166]:
for instance in hogwarts['griffendor']:
    instance.tell_pet()

Harry Potter's owl is called Hedwig.
Ron Weasley's scabbers is called Martin.
Hermine Granger has no pet.


In [167]:
for house, wizards in hogwarts.items():
    for wizard in wizards:
        wizard.tell_pet()
        wizard.expecto_patronum()

Harry Potter's owl is called Hedwig.
A stag appears.
Ron Weasley's scabbers is called Martin.
A jack russel terrier appears.
Hermine Granger has no pet.
A otter appears.
Newt Scamander has no pet.
Newt Scamander has no patronus.
Luna Lovegood's pygmy puff is called Pigwidgeon.
A hare appears.
Draco Melfoy's owl is called Buckbeak.
Draco Melfoy has no patronus.


## Well done!!!